// src/features/about/Achievements.svelte
<script>
  const achievements = [
    {
      icon: "🏆",
      rarity: "LEGENDARY",
      title: "DATA PIPELINE ARCHITECT",
      desc: "Designed ETL systems processing +1M records daily",
      accentColor: "var(--power-bi-yellow)"
    },
    {
      icon: "🛡️",
      rarity: "EPIC",
      title: "ZERO BREACH RECORD",
      desc: "3+ years maintaining enterprise security standards",
      accentColor: "var(--neon-cyan)"
    },
    {
      icon: "🤖",
      rarity: "RARE",
      title: "ML MODEL DEPLOYER",
      desc: "Successfully deployed models to cloud TPU infrastructure",
      accentColor: "var(--hyper-purple)"
    },
    {
      icon: "📊",
      rarity: "EPIC",
      title: "BI DASHBOARD MASTER",
      desc: "Created executive dashboards for +5 organizations",
      accentColor: "var(--power-bi-yellow)"
    }
  ];
</script>

<div class="achievements-section">
  <h3 class="achievements-title">[ ACHIEVEMENTS_UNLOCKED ]</h3>
  
  <div class="achievements-grid">
    {#each achievements as achievement}
      <div 
        class="achievement-card" 
        style="--accent-color: {achievement.accentColor};"
      >
        <span class="achievement-icon">{achievement.icon}</span>
        <div class="achievement-content">
          <span class="achievement-rarity">{achievement.rarity}</span>
          <span class="achievement-title">{achievement.title}</span>
          <span class="achievement-desc">{achievement.desc}</span>
        </div>
      </div>
    {/each}
  </div>
</div>

<style>
  .achievements-section {
    padding: 32px 0;
  }

  .achievements-title {
    font-size: 10px;
    color: var(--hyper-purple);
    text-align: center;
    margin-bottom: 32px;
    letter-spacing: 1px;
  }

  .achievements-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
    gap: 16px;
  }

  .achievement-content {
    display: flex;
    flex-direction: column;
  }
</style>

// src/components/ui/Achievements.tsx
export function Achievements() {
    const unlockedAchievements = [
        {
            id: "neural_navigator",
            title: "NEURAL NAVIGATOR",
            desc: "Sentiment analysis using DistilBERT & ABSA for restaurant reviews.",
            icon: "🧠",
            rarity: "LEGENDARY",
            color: "var(--neon-cyan)"
        },
        {
            id: "data_oracle",
            title: "DATA ORACLE",
            desc: "Engineered a high-performance Movie Recommender system.",
            icon: "🔮",
            rarity: "EPIC",
            color: "var(--hyper-purple)"
        },
        {
            id: "hardware_hacker",
            title: "HARDWARE HACKER",
            desc: "Optimized AlphaNet models to run on TPU/Cloud infrastructure.",
            icon: "⚡",
            rarity: "RARE",
            color: "var(--orange-burnt)"
        },
        {
            id: "fullstack_hero",
            title: "SYSTEM ARCHITECT",
            desc: "Deployed secure enterprise-grade logistics & inventory ecosystems.",
            icon: "🏗️",
            rarity: "RARE",
            color: "var(--teal-dark)"
        },
        {
            id: "kpi_architect",
            title: "KPI ARCHITECT",
            desc: "Built complex Power BI Dashboards for customer loyalty and satisfaction tracking.",
            icon: "📊",
            rarity: "EPIC",
            color: "#F2C811"
        }
    ];

    return (
        <div style={{ marginTop: "64px" }}>
            <h3 style={{
                color: "var(--orange-burnt)",
                fontSize: "10px",
                marginBottom: "32px",
                textAlign: "center"
            }}>
                [ UNLOCKED_ACHIEVEMENTS ]
            </h3>

            <div style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
                gap: "20px"
            }}>
                {unlockedAchievements.map((achiv) => (
                    <div
                        key={achiv.id}
                        className="achievement-card"
                        style={{ "--accent-color": achiv.color } as any}
                    >
                        <div className="achievement-icon">{achiv.icon}</div>
                        <div>
                            <div className="achievement-rarity">[{achiv.rarity}]</div>
                            <div className="achievement-title">{achiv.title}</div>
                            <div className="achievement-desc">{achiv.desc}</div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
